configs:
  cm:
    # Ensures Argo generates correct external links/redirects
    url: https://argocd.michaellutz.org
  params:
    # Tells the chart/server to run without TLS behind ingress
    server.insecure: "true"

server:
  ingress:
    enabled: true

    # Traefik on k3s
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: traefik

    # Hostname you will publish via Cloudflare Tunnel
    hostname: argocd.michaellutz.org
    path: /
    pathType: Prefix
    # Option A: no TLS in-cluster
    tls: false
