apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture-it
  namespace: mlutz-apps
  labels:
    app: picture-it
spec:
  replicas: 1
  selector:
    matchLabels:
      app: picture-it
  template:
    metadata:
      labels:
        app: picture-it
    spec:
      containers:
      - name: picture-it
        image: ghcr.io/mlutz-devops/picture-it:v0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
