apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: picture-it-ingress
  namespace: picture-it
spec:
  rules:
  - host: picture-it.michaellutz.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: picture-it-service
            port:
              number: 80

